// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfoResponse struct {
	UserId    int    `json:"user_id"`
	UserrName string `json:"username"`
}
