// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package usercreate

import (
	"context"

	"go-zero/feng/rpc_study/user_group/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserCreateRequest  = user.UserCreateRequest
	UserCreateResponse = user.UserCreateResponse
	UserInfoRequest    = user.UserInfoRequest
	UserInfoResponse   = user.UserInfoResponse

	UserCreate interface {
		UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	}

	defaultUserCreate struct {
		cli zrpc.Client
	}
)

func NewUserCreate(cli zrpc.Client) UserCreate {
	return &defaultUserCreate{
		cli: cli,
	}
}

func (m *defaultUserCreate) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	client := user.NewUserCreateClient(m.cli.Conn())
	return client.UserCreate(ctx, in, opts...)
}
